export type SignOffStatus = 'signed' | 'pending' | 'rejected' | 'none';

export interface SignOffRecord {
  date: string;
  status: SignOffStatus;
  signedBy?: string;
  signedAt?: string;
  comment?: string;
}

export interface BookComment {
  id: string;
  bookId: string;
  date: string; // The reporting date this comment is about
  authorName: string;
  authorRole: 'trader' | 'product_controller' | 'desk_head';
  content: string;
  createdAt: string;
  parentId?: string; // For replies
  readByPC?: boolean; // Whether product controller has read this comment
  readByTrader?: boolean; // Whether trader has read this comment
}

export interface Book {
  id: string;
  name: string;
  desk: string;
  primaryTrader: string;
  secondaryTrader: string;
  deskHead: string;
  productController: string;
  isRetired: boolean;
  signOffs: SignOffRecord[];
  comments: BookComment[];
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: 'trader' | 'product_controller' | 'desk_head';
}

// Bank holidays storage key
const BANK_HOLIDAYS_KEY = 'sefe_bank_holidays';

// Get bank holidays from localStorage
export function getBankHolidays(): string[] {
  try {
    const stored = localStorage.getItem(BANK_HOLIDAYS_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

// Add a bank holiday
export function addBankHoliday(date: string): void {
  const holidays = getBankHolidays();
  if (!holidays.includes(date)) {
    holidays.push(date);
    localStorage.setItem(BANK_HOLIDAYS_KEY, JSON.stringify(holidays));
  }
}

// Remove a bank holiday
export function removeBankHoliday(date: string): void {
  const holidays = getBankHolidays().filter(h => h !== date);
  localStorage.setItem(BANK_HOLIDAYS_KEY, JSON.stringify(holidays));
}

// Check if a date is a bank holiday
export function isBankHoliday(date: string): boolean {
  return getBankHolidays().includes(date);
}

// Get last N working days (excluding weekends and bank holidays)
// Returns dates in descending order (most recent first)
export function getLastWorkingDays(count: number): string[] {
  const days: string[] = [];
  let date = new Date();
  const bankHolidays = getBankHolidays();
  
  while (days.length < count) {
    date.setDate(date.getDate() - 1);
    const dayOfWeek = date.getDay();
    const dateStr = date.toISOString().split('T')[0];
    
    // Skip weekends and bank holidays
    if (dayOfWeek !== 0 && dayOfWeek !== 6 && !bankHolidays.includes(dateStr)) {
      days.push(dateStr);
    }
  }
  
  // Already in descending order (most recent first)
  return days;
}

export function formatWorkingDay(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-GB', { 
    weekday: 'short', 
    day: '2-digit', 
    month: 'short' 
  });
}

// Generate sign-offs for 10 working days to support extended date range
const workingDays = getLastWorkingDays(10);

const generateRandomSignOffs = (): SignOffRecord[] => {
  const statuses: SignOffStatus[] = ['signed', 'pending', 'rejected'];
  const weights = [0.65, 0.25, 0.1]; // More signed than pending/rejected, no "none" status
  
  return workingDays.map((date, index) => {
    // Most recent day (index 0) is always pending (new day starts with pending)
    if (index === 0) {
      return {
        date,
        status: 'pending' as SignOffStatus,
        signedBy: undefined,
        signedAt: undefined,
        comment: undefined,
      };
    }
    
    const rand = Math.random();
    let status: SignOffStatus = 'signed';
    let cumulative = 0;
    for (let i = 0; i < weights.length; i++) {
      cumulative += weights[i];
      if (rand < cumulative) {
        status = statuses[i];
        break;
      }
    }
    
    return {
      date,
      status,
      signedBy: status === 'signed' ? 'Auto-signed' : undefined,
      signedAt: status === 'signed' ? '09:45' : undefined,
      comment: status === 'rejected' ? 'Variance above threshold' : undefined,
    };
  });
};

// Real book data from SEFE
const bookData = [
  { name: "Area D", primaryTrader: "Robert Allan", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "Asset Optimisation", primaryTrader: "Andrey Selikhov", secondaryTrader: "Ali Farah", deskHead: "Dom Both", desk: "Energy Transition", productController: "Kelly Lim" },
  { name: "CEGH Storage", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "CONTI_GAS_STRUCTURES_6", primaryTrader: "Paul Smith", secondaryTrader: "Ghassan Matta", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "Capital Solutions", primaryTrader: "Alexander Welch", secondaryTrader: "Sebastian Dorkel", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Carbon Cross Commodity", primaryTrader: "Mauricio Cepeda", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "Carbon Management Position", primaryTrader: "Mauricio Cepeda", secondaryTrader: "Ghassan Matta", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Carbon Options", primaryTrader: "Mauricio Cepeda", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Carbon Trading", primaryTrader: "Mauricio Cepeda", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Carbon Volumetric Position", primaryTrader: "Mauricio Cepeda", secondaryTrader: "Alexander Welch", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Clean Spark Spread and UK Prompt Power", primaryTrader: "Michael Brewin", secondaryTrader: "Mathieu Pourcel", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "Consolidated LNG Portfolio Position and Valuation", primaryTrader: "Joseph Robinson", secondaryTrader: "Mathieu Marniquet", deskHead: "Jean-Manuel Conil-Lacoste", desk: "LNG", productController: "Khor Mei Leng" },
  { name: "Consolidated Oil Trading", primaryTrader: "Mark Rogers", secondaryTrader: "Ghassan Matta", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Consolidated Treasury P&L", primaryTrader: "Yulia Tikhonova", secondaryTrader: "Jessica Heilpern", deskHead: "Ben Street", desk: "Treasury", productController: "Khor Mei Leng" },
  { name: "Conti Deal Mgmt", primaryTrader: "Thomas Sparkes", secondaryTrader: "Ugo Iozzo", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Demi Comitis" },
  { name: "Conti Flow", primaryTrader: "Michael Brewin", secondaryTrader: "Connor Routh", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Conti Fuel Spread", primaryTrader: "Mathieu Pourcel", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "Conti Futures", primaryTrader: "Alexander Welch", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "Conti Gas Structure 1", primaryTrader: "Christopher Holmes", secondaryTrader: "Jake Murphy", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "Conti Gas Structure 2", primaryTrader: "Mark Rogers", secondaryTrader: "Paul Smith", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "Conti Gas Structure 4", primaryTrader: "Mark Rogers", secondaryTrader: "Christopher Holmes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "Conti Gas Structure 5", primaryTrader: "Mark Rogers", secondaryTrader: "Christopher Holmes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "Conti Interconnectors Power", primaryTrader: "Mathieu Pourcel", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Ruslan Markov" },
  { name: "Conti Profile", primaryTrader: "Michael Brewin", secondaryTrader: "Connor Routh", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Conti Spark Spread", primaryTrader: "Mathieu Pourcel", secondaryTrader: "Michael Brewin", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Conti Structured", primaryTrader: "Mathieu Pourcel", secondaryTrader: "Robbert van den Bergh", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "DA Index Management", primaryTrader: "Mark Prenty", secondaryTrader: "Robert Allan", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "Deal Flow", primaryTrader: "Robert Allan", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "Digital Carbon", primaryTrader: "Rhidhi Sheth", secondaryTrader: "George Mikhalev", deskHead: "Dom Both", desk: "Digital Trading", productController: "Stefanie Shi" },
  { name: "Dunkerque Regas", primaryTrader: "Mathieu Marniquet", secondaryTrader: "Joseph Robinson", deskHead: "Jean-Manuel Conil-Lacoste", desk: "LNG", productController: "Jorge Barbera" },
  { name: "Dutch Retail", primaryTrader: "Joshua Thomas", secondaryTrader: "Tomos Edwards", deskHead: "Marcus Bredin", desk: "SPO", productController: "Demi Comitis" },
  { name: "Dutch Transportation", primaryTrader: "Peter Smit", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "EE Flow", primaryTrader: "Michael Brewin", secondaryTrader: "Jonathan Taubert", deskHead: "Michael Brewin", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "EE Gas Flow", primaryTrader: "Robert Allan", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "EU Clean Sparks", primaryTrader: "Thomas Sparkes", secondaryTrader: "Ugo Iozzo", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "EU/UK Cross Commodity", primaryTrader: "Tomos Edwards", secondaryTrader: "Michael Brewin", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "Embedded Generation", primaryTrader: "Andrey Selikhov", secondaryTrader: "Ali Farah", deskHead: "Dom Both", desk: "Energy Transition", productController: "Demi Comitis" },
  { name: "Etzel", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "Etzel Virtual Storage", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "Euro Deal Management 2", primaryTrader: "Peter Smit", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Euro Deal Management 3", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Euro Deal Management 4", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Euro Deal Management 6", primaryTrader: "Mariia Libermann", secondaryTrader: "Eddie Ramprakash", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "Euro Deal Management 7", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Euro Power", primaryTrader: "Mathieu Pourcel", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "FR/UK & UK/NL Power", primaryTrader: "Jonathan Taubert", secondaryTrader: "Michael Brewin", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Ruslan Markov" },
  { name: "FX Consolidated", primaryTrader: "Jeremy Burns", secondaryTrader: "Derek Caldwell", deskHead: "Jeremy Burns", desk: "FX", productController: "Khor Mei Leng" },
  { name: "Flex & Bal Retail", primaryTrader: "Tomos Edwards", secondaryTrader: "Joshua Thomas", deskHead: "Marcus Bredin", desk: "SPO", productController: "James Thomas" },
  { name: "France Retail", primaryTrader: "Joshua Thomas", secondaryTrader: "Tomos Edwards", deskHead: "Marcus Bredin", desk: "SPO", productController: "Demi Comitis" },
  { name: "Futures", primaryTrader: "Alexander Welch", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "Gas Digital", primaryTrader: "Rhidhi Sheth", secondaryTrader: "George Mikhalev", deskHead: "Dom Both", desk: "Digital Trading", productController: "Stefanie Shi" },
  { name: "Gas Strategic Position", primaryTrader: "Jijia Zuo", secondaryTrader: "Ghassan Matta", deskHead: "Ghassan Matta", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "German Regas", primaryTrader: "Mathieu Marniquet", secondaryTrader: "Joseph Robinson", deskHead: "Jean-Manuel Conil-Lacoste", desk: "LNG", productController: "Jorge Barbera" },
  { name: "German Spark Spread", primaryTrader: "Nikolaos Troullinos", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "German Storage", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "German White Label PPAs", primaryTrader: "Andrey Selikhov", secondaryTrader: "Ali Farah", deskHead: "Dom Both", desk: "Energy Transition", productController: "Kelly Lim" },
  { name: "Hedge Storage Gas UK", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "IRE Gas", primaryTrader: "Robert Allan", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "Index Management", primaryTrader: "Robert Allan", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Index Swing, Stor & Struc Opt", primaryTrader: "Anthony Antunes", secondaryTrader: "Misha Wolynski", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Intraday Imbalance Summary", primaryTrader: "Ben Cranny", secondaryTrader: "Callum Sinclair", deskHead: "Dom Both", desk: "Power Intraday", productController: "Stefanie Shi" },
  { name: "Intraday Joint Venture", primaryTrader: "Ben Cranny", secondaryTrader: "Callum Sinclair", deskHead: "Dom Both", desk: "Power Intraday", productController: "Veronika Yastrebova" },
  { name: "Intraday Power", primaryTrader: "Ben Cranny", secondaryTrader: "Callum Sinclair", deskHead: "Dom Both", desk: "Power Intraday", productController: "Veronika Yastrebova" },
  { name: "Intraday Systematic", primaryTrader: "Ben Cranny", secondaryTrader: "Callum Sinclair", deskHead: "Dom Both", desk: "Power Intraday", productController: "Veronika Yastrebova" },
  { name: "Joint Strategy P&L & Position", primaryTrader: "Alastair Hill", secondaryTrader: "Nathan Dixon", deskHead: "Nathan Dixon", desk: "EP", productController: "Vinny Sharma" },
  { name: "LNG Derivatives", primaryTrader: "Anthony Antunes", secondaryTrader: "Misha Wolynski", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "LNG In Tank", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "LNG Portfolio FFA Trading", primaryTrader: "Peter Melrose", secondaryTrader: "Shiang Yng Ong", deskHead: "Mikhail Potapenko", desk: "LNG", productController: "Khor Mei Leng" },
  { name: "LNG Swaps Exchange Position and Valuation", primaryTrader: "Joseph Robinson", secondaryTrader: "Sabri Benharrats", deskHead: "Ghassan Matta", desk: "LNG", productController: "Khor Mei Leng" },
  { name: "LNGT Prop", primaryTrader: "Jean-Manuel Conil-Lacoste", secondaryTrader: "Alessandro Mori", deskHead: "Jean-Manuel Conil-Lacoste", desk: "LNG", productController: "Ero Kapatos" },
  { name: "LNG_FO_GAIL_RNST_26_SLNG", primaryTrader: "Jijia Zuo", secondaryTrader: "Sabri Benharrats", deskHead: "Ghassan Matta", desk: "LNG", productController: "Ero Kapatos" },
  { name: "LNG_FO_GAIL_UQT_26_SLNG", primaryTrader: "Jijia Zuo", secondaryTrader: "Sabri Benharrats", deskHead: "Ghassan Matta", desk: "LNG", productController: "Ero Kapatos" },
  { name: "MANAGEMENT_FX_XCDY-DESK_SMT", primaryTrader: "Ghassan Matta", secondaryTrader: "Mark Rogers", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "MOD Index Management", primaryTrader: "Stefano Nanni", secondaryTrader: "Marcus Bredin", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Demi Comitis" },
  { name: "Macro Trading", primaryTrader: "Olaf Dreyer", secondaryTrader: "Morgan Corran", deskHead: "Edward Gomersall", desk: "Gas & Hub", productController: "James Thomas" },
  { name: "Management Gas", primaryTrader: "Alexander Welch", secondaryTrader: "Sebastian Dorkel", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Stefanie Shi" },
  { name: "Medium Term Euro Power", primaryTrader: "Mathieu Pourcel", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "Metal Trading", primaryTrader: "Jiadong Wang", secondaryTrader: "George Mikhalev", deskHead: "Dom Both", desk: "Metal Trading", productController: "Jasdeep Dhaliwal" },
  { name: "Metals Financing", primaryTrader: "Paul Crone", secondaryTrader: "Brandon Rust", deskHead: "Dom Both", desk: "Metal Trading", productController: "Jasdeep Dhaliwal" },
  { name: "Metals Strat", primaryTrader: "Paul Crone", secondaryTrader: "Brandon Rust", deskHead: "Dom Both", desk: "Metal Trading", productController: "Jasdeep Dhaliwal" },
  { name: "Metals Tact 1", primaryTrader: "Paul Crone", secondaryTrader: "Brandon Rust", deskHead: "Dom Both", desk: "Metal Trading", productController: "Jasdeep Dhaliwal" },
  { name: "Metals Tact 2", primaryTrader: "Paul Crone", secondaryTrader: "Brandon Rust", deskHead: "Dom Both", desk: "Metal Trading", productController: "Jasdeep Dhaliwal" },
  { name: "NAFTA Storage", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "NBP Deal Mgmt", primaryTrader: "Thomas Sparkes", secondaryTrader: "Ugo Iozzo", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "Oil Hedging Position and Valuation", primaryTrader: "Joseph Robinson", secondaryTrader: "Mathieu Marniquet", deskHead: "Ghassan Matta", desk: "LNG", productController: "Khor Mei Leng" },
  { name: "Open Retail", primaryTrader: "Marcus Bredin", secondaryTrader: "Joshua Thomas", deskHead: "Ghassan Matta", desk: "SPO", productController: "James Thomas" },
  { name: "Open Storage 1", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "Open Storage 4", primaryTrader: "Andrew Shepherd", secondaryTrader: "Deepesh Patel", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Origination Prop P&L & Position", primaryTrader: "Alastair Hill", secondaryTrader: "Nathan Dixon", deskHead: "Nathan Dixon", desk: "EP", productController: "Vinny Sharma" },
  { name: "PEG Storage", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "Physical Metals", primaryTrader: "Paul Crone", secondaryTrader: "Brandon Rust", deskHead: "Dom Both", desk: "Metal Trading", productController: "Jasdeep Dhaliwal" },
  { name: "Power Analyst", primaryTrader: "Alexander Richardson", secondaryTrader: "Michael Brewin", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "Power Derivatives", primaryTrader: "Anthony Antunes", secondaryTrader: "Misha Wolynski", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Power Digital", primaryTrader: "Rhidhi Sheth", secondaryTrader: "George Mikhalev", deskHead: "Dom Both", desk: "Digital Trading", productController: "Stefanie Shi" },
  { name: "Power FX Exposure", primaryTrader: "Laurent Maurice-Vallerey", secondaryTrader: "Mathieu Pourcel", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "James Thomas" },
  { name: "Power Imbalance Summary", primaryTrader: "Power Operations", secondaryTrader: "Paul Bajan", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Stefanie Shi" },
  { name: "Power Management", primaryTrader: "Michael Brewin", secondaryTrader: "Mathieu Pourcel", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "James Thomas" },
  { name: "Power Ops", primaryTrader: "Power Operations", secondaryTrader: "Power Ops", deskHead: "Dom Both", desk: "Energy Transition", productController: "Stefanie Shi" },
  { name: "Power Prop Options", primaryTrader: "Anthony Antunes", secondaryTrader: "Misha Wolynski", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Prop 10", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Prop 12", primaryTrader: "Joshua Thomas", secondaryTrader: "Marcus Bredin", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Prop 13", primaryTrader: "Thomas Sparkes", secondaryTrader: "Ugo Iozzo", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "Prop 15", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Prop 16", primaryTrader: "Chris Holmes", secondaryTrader: "Jake Murphy", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Prop 18", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Prop 2", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Prop 3", primaryTrader: "Peter Smit", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Prop 4", primaryTrader: "Mark Prenty", secondaryTrader: "Robert Allan", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Prop 5", primaryTrader: "Jake Murphy", secondaryTrader: "Christopher Holmes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Prop 6", primaryTrader: "Jake Murphy", secondaryTrader: "Christopher Holmes", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Prop 7", primaryTrader: "Robert Allan", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Prop 8", primaryTrader: "Josh Atherall", secondaryTrader: "Marcus Bredin", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Prop 9", primaryTrader: "Mariia Libermann", secondaryTrader: "Eddie Ramprakash", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Prop Derivatives 1", primaryTrader: "Misha Wolynski", secondaryTrader: "Anthony Antunes", deskHead: "Sebastian Dorkel", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Prop Derivatives 2", primaryTrader: "Misha Wolynski", secondaryTrader: "Anthony Antunes", deskHead: "Sebastian Dorkel", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Prop Derivatives 3 (Derivs Team Prop)", primaryTrader: "Misha Wolynski", secondaryTrader: "Anthony Antunes", deskHead: "Sebastian Dorkel", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Prop Derivatives 4", primaryTrader: "Misha Wolynski", secondaryTrader: "Anthony Antunes", deskHead: "Sebastian Dorkel", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Prop Options Gas", primaryTrader: "Anthony Antunes", secondaryTrader: "Misha Wolynski", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Lule Halimi" },
  { name: "Prop Sparks", primaryTrader: "Anthony Antunes", secondaryTrader: "Misha Wolynski", deskHead: "Sebastian Dorkel", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Prop Sparks 2", primaryTrader: "Anthony Antunes", secondaryTrader: "Misha Wolynski", deskHead: "Sebastian Dorkel", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "Prop Transport 2", primaryTrader: "Peter Smit", secondaryTrader: "Robert Allan", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Veronika Yastrebova" },
  { name: "ROCs, GOOs & REGO", primaryTrader: "Sonia Gulati", secondaryTrader: "Toon Van De Plas", deskHead: "Dom Both", desk: "Energy Transition", productController: "Kelly Lim" },
  { name: "Regas Zee", primaryTrader: "Mathieu Marniquet", secondaryTrader: "Joseph Robinson", deskHead: "Jean-Manuel Conil-Lacoste", desk: "LNG", productController: "Jorge Barbera" },
  { name: "Retail Power", primaryTrader: "Tomos Edwards", secondaryTrader: "Joshua Thomas", deskHead: "Marcus Bredin", desk: "SPO", productController: "James Thomas" },
  { name: "SEFE LNG P&L and Exposure", primaryTrader: "Shiang Yng Ong", secondaryTrader: "Zhenxing Teo", deskHead: "Jean-Manuel Conil-Lacoste", desk: "LNG", productController: "Kelly Lim" },
  { name: "SMTS LNG P&L and Exposure", primaryTrader: "Shiang Yng Ong", secondaryTrader: "Zhenxing Teo", deskHead: "Jean-Manuel Conil-Lacoste", desk: "LNG", productController: "Kelly Lim" },
  { name: "SOCAR Index", primaryTrader: "Ugo Iozzo", secondaryTrader: "Thomas Sparkes", deskHead: "Ghassan Matta", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "SPO Analyst", primaryTrader: "Joshua Frost", secondaryTrader: "Tomos Edwards", deskHead: "Marcus Bredin", desk: "SPO", productController: "James Thomas" },
  { name: "SPO DE Power Flow", primaryTrader: "Tomos Edwards", secondaryTrader: "Joshua Thomas", deskHead: "Marcus Bredin", desk: "SPO", productController: "Jonas Koch" },
  { name: "SPO Index", primaryTrader: "Marcus Bredin", secondaryTrader: "Josh Atherall", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Demi Comitis" },
  { name: "SPO MAV Index", primaryTrader: "Stefano Nanni", secondaryTrader: "Marcus Bredin", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "Sales Gas", primaryTrader: "Commercial Process & Control", secondaryTrader: "Commercial Process & Control", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Stefanie Shi" },
  { name: "Short Term I/C Power", primaryTrader: "Mathieu Pourcel", secondaryTrader: "Laurent Maurice-Vallerey", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Ruslan Markov" },
  { name: "Spanish Regas", primaryTrader: "David Gooddy", secondaryTrader: "Alessandro Mori", deskHead: "Jean-Manuel Conil-Lacoste", desk: "LNG", productController: "Jorge Barbera" },
  { name: "Strat Positions Power", primaryTrader: "Mathieu Pourcel", secondaryTrader: "Michael Brewin", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "Systematic Cross Com - DT²", primaryTrader: "Rhidhi Sheth", secondaryTrader: "George Mikhalev", deskHead: "Dom Both", desk: "Digital Trading", productController: "Stefanie Shi" },
  { name: "True North", primaryTrader: "Robert Allan", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Demi Comitis" },
  { name: "UK Deal Flow Power", primaryTrader: "Michael Brewin", secondaryTrader: "Jonathan Taubert", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "UK Retail Fixed", primaryTrader: "Tomos Edwards", secondaryTrader: "Joshua Thomas", deskHead: "Marcus Bredin", desk: "SPO", productController: "James Thomas" },
  { name: "UK Spark Spread", primaryTrader: "Jonathan Taubert", secondaryTrader: "Michael Brewin", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Demi Comitis" },
  { name: "UK Stack & DA Conti Stack", primaryTrader: "Erenjeeve Hothi", secondaryTrader: "Jonathan Taubert", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "James Thomas" },
  { name: "UK Storage", primaryTrader: "Deepesh Patel", secondaryTrader: "Andrew Shepherd", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "UK Storage 2", primaryTrader: "Alexander Welch", secondaryTrader: "Sebastian Dorkel", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Kelly Lim" },
  { name: "US Digital Trading", primaryTrader: "Rhidhi Sheth", secondaryTrader: "George Mikhalev", deskHead: "Dom Both", desk: "Digital Trading", productController: "Stefanie Shi" },
  { name: "WIEE Transport and Flow", primaryTrader: "Sergey Ayrapetyan", secondaryTrader: "Karoly Schmidt", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "WINGAS Deal Management", primaryTrader: "Mark Prenty", secondaryTrader: "Robert Allan", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
  { name: "XCom SMT", primaryTrader: "Paul Smith", secondaryTrader: "Ghassan Matta", deskHead: "Ghassan Matta", desk: "Cross Commodity", productController: "Veronika Yastrebova" },
  { name: "ZTP WD BALANCING", primaryTrader: "Robert Allan", secondaryTrader: "Mark Prenty", deskHead: "Ed Humphreys", desk: "Gas & Hub", productController: "Ruslan Markov" },
];

const workingDaysForComments = getLastWorkingDays(5);

// Generate sample comments for some books
const generateSampleComments = (bookId: string, bookName: string, primaryTrader: string, deskHead: string): BookComment[] => {
  const shouldHaveComments = Math.random() > 0.7; // 30% of books have comments
  if (!shouldHaveComments) return [];

  const comments: BookComment[] = [];
  const numComments = Math.floor(Math.random() * 3) + 1;

  const sampleMessages = [
    "Please review the variance on this report",
    "P&L figures look unusual for this period",
    "Need clarification on the hedge positions",
    "Waiting for updated market data",
    "Position reconciliation pending",
    "Query on the MTM calculation",
  ];

  for (let i = 0; i < numComments; i++) {
    const isFromDeskHead = Math.random() > 0.7;
    const hoursAgo = Math.floor(Math.random() * 48);
    const createdAt = new Date(Date.now() - hoursAgo * 60 * 60 * 1000).toISOString();
    const authorRole: 'trader' | 'desk_head' = isFromDeskHead ? 'desk_head' : 'trader';
    
    // Trader/desk head comments are unread by PC
    // Mark some as read randomly for demo (recent comments more likely to be unread)
    const isRecent = hoursAgo < 12;
    
    comments.push({
      id: `comment-${bookId}-${i}`,
      bookId,
      date: workingDaysForComments[Math.floor(Math.random() * workingDaysForComments.length)],
      authorName: isFromDeskHead ? deskHead : primaryTrader,
      authorRole,
      content: sampleMessages[Math.floor(Math.random() * sampleMessages.length)],
      createdAt,
      readByPC: !isRecent || Math.random() > 0.6, // Recent comments are more likely unread
      readByTrader: true, // Trader's own comments or desk head comments are "read" by traders
    });
  }

  return comments;
};

// Sample retired books - mark a few books as retired for demo
const retiredBookNames = [
  "CONTI_GAS_STRUCTURES_6",
  "Consolidated Treasury P&L",
  "MANAGEMENT_FX_XCDY-DESK_SMT",
];

// Retired books data - no trader assignments required
const retiredBooksData = [
  { name: "AB_GAS_UK", desk: "Gas" },
  { name: "AGENCY_GAS_UK", desk: "Gas" },
  { name: "ALGO_10_FX_UK", desk: "FX" },
  { name: "ALGO_11_FX_UK", desk: "FX" },
  { name: "ALGO_12_FX_UK", desk: "FX" },
  { name: "ALGO_13_FX_UK", desk: "FX" },
  { name: "ALGO_14_FX_UK", desk: "FX" },
  { name: "ALGO_15_FX_UK", desk: "FX" },
  { name: "ALGO_16_FX_UK", desk: "FX" },
  { name: "ALGO_17_FX_UK", desk: "FX" },
  { name: "ALGO_18_FX_UK", desk: "FX" },
  { name: "ALGO_19_FX_UK", desk: "FX" },
  { name: "ALGO_2_FX_UK", desk: "FX" },
  { name: "ALGO_20_FX_UK", desk: "FX" },
  { name: "ALGO_3_FX_UK", desk: "FX" },
  { name: "ALGO_4_FX_UK", desk: "FX" },
  { name: "ALGO_5_FX_UK", desk: "FX" },
  { name: "ALGO_6_FX_UK", desk: "FX" },
  { name: "ALGO_7_FX_UK", desk: "FX" },
  { name: "ALGO_8_FX_UK", desk: "FX" },
  { name: "ALGO_9_FX_UK", desk: "FX" },
  { name: "ALGO_FX_UK", desk: "FX" },
  { name: "ALGO_MAPPING_FX_UK", desk: "FX" },
  { name: "ANALYST_PWR_UK", desk: "Power" },
  { name: "ANTARGAZ_ET_GAS_UK", desk: "Gas" },
  { name: "ARCELOR_ET_GAS_UK", desk: "Gas" },
  { name: "AREA_D_GAS_UK", desk: "Gas" },
  { name: "ARENH_PWR_UK", desk: "Power" },
  { name: "ASSET_OPS_PWR_UK", desk: "Power" },
  { name: "AT_CZ_PWR_UK", desk: "Power" },
  { name: "AT_HU_PWR_UK", desk: "Power" },
  { name: "BAL_DGTL_UK", desk: "Power" },
  { name: "BAL2_DGTL_UK", desk: "Power" },
  { name: "BAL3_DGTL_UK", desk: "Power" },
  { name: "BALTIC_CLEAN_STORAGE_CH", desk: "OIL" },
  { name: "BASIS_PROP_GAS_UK", desk: "Gas" },
  { name: "BBL_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "BE_RE_GAS_UK", desk: "Gas" },
  { name: "BE_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "BE_UK_PWR_UK", desk: "Power" },
  { name: "BE_UK2_PWR_UK", desk: "Power" },
  { name: "BERG_STOR_GAS_UK", desk: "Gas" },
  { name: "BIOMASS_CB_SG", desk: "Carbon" },
  { name: "BUS_DEV_C&SE_EU_CH", desk: "Carbon" },
  { name: "CAPACITY_GAS_CH", desk: "Gas" },
  { name: "CAPACITY_POWER_CH", desk: "Power" },
  { name: "CARB_COMP_PROP_EP_UK", desk: "Carbon" },
  { name: "CARBON_1_DGTL_UK", desk: "Carbon" },
  { name: "CARBON_2_DGTL_UK", desk: "Carbon" },
  { name: "CARBON_CROSS_COMM_PWR_UK", desk: "Carbon" },
  { name: "CARBON_FUNDING_PWR_UK", desk: "Carbon" },
  { name: "CARBON_FUTURES_PWR_UK", desk: "Carbon" },
  { name: "CARBON_NGEO_EP_UK", desk: "Carbon" },
  { name: "CARBON_OPTIONS_GAS_UK", desk: "Carbon" },
  { name: "CARBON_REPO_PWR_UK", desk: "Carbon" },
  { name: "CARBON_REPO_SG", desk: "Carbon" },
  { name: "CARBON_RETAIL_SALES_PWR", desk: "Carbon" },
  { name: "CARBON_SALES_PWR_UK", desk: "Carbon" },
  { name: "CARBON_STRATPOSITION_PWR_UK", desk: "Carbon" },
  { name: "CARBON_STRUCT_PWR_UK", desk: "Carbon" },
  { name: "CARBON_VCU_PWR_UK", desk: "Carbon" },
  { name: "CARBON2_PWR_UK", desk: "Carbon" },
  { name: "CARBONFX_CB_SG", desk: "Carbon" },
  { name: "CARBONFX_CB_UK", desk: "Carbon" },
  { name: "CARBONTRADE_PWR_UK", desk: "Carbon" },
  { name: "CEGH_2_STOR_GAS_UK", desk: "Gas" },
  { name: "CEGH_3_STOR_GAS_UK", desk: "Gas" },
  { name: "CEGH_B_STOR_GAS_UK", desk: "Gas" },
  { name: "CEGH_S_STOR_GAS_UK", desk: "Gas" },
  { name: "CER_OPT_PWR_UK", desk: "Carbon" },
  { name: "CER_PORTFOLIO_PWR_UK", desk: "Carbon" },
  { name: "CER_PROJ_PWR_SG", desk: "Carbon" },
  { name: "CER_PROJ_PWR_UK", desk: "Carbon" },
  { name: "CLEAN_OIL_US", desk: "OIL" },
  { name: "CLOSEOUT_AVU", desk: "Gas" },
  { name: "CLOSEOUT_CASTLETON_GAS_UK", desk: "Gas" },
  { name: "CLOSEOUT_EROVA_PWR_UK", desk: "Power" },
  { name: "CLOSEOUT_FX_UK", desk: "FX" },
  { name: "CLOSEOUT_GAS_UK", desk: "Gas" },
  { name: "CLOSEOUT_METI_GAS_UK", desk: "Gas" },
  { name: "CLOSEOUT_PWR_UK", desk: "Power" },
  { name: "COAL_OPTIONS_PWR_UK", desk: "Power" },
  { name: "COAL_ORIG_PWR_UK", desk: "Power" },
  { name: "COAL_PROP_OPTIONS_GAS_UK", desk: "Power" },
  { name: "COAL_PWR_UK", desk: "Power" },
  { name: "COAL_SPREADS_PWR_UK", desk: "Power" },
  { name: "COAL_SWAP_SG", desk: "Power" },
  { name: "CONDENSATE_PHY_HEDGE_SG", desk: "OIL" },
  { name: "CONTI_ANALYST_MT_PWR_UK", desk: "Power" },
  { name: "CONTI_ANALYST_ST_PWR_UK", desk: "Power" },
  { name: "CONTI_BOOK_BAL_GAS_UK", desk: "Gas" },
  { name: "CONTI_CURVE_PWR_UK", desk: "Power" },
  { name: "CONTI_DEAL_MGMT_GAS_UK", desk: "Gas" },
  { name: "CONTI_FLOW_2_PWR_UK", desk: "Power" },
  { name: "CONTI_FLOW_PWR_UK", desk: "Power" },
  { name: "CONTI_FUEL_SPREADS_PWR_UK", desk: "Power" },
  { name: "CONTI_FUTURES_GAS_UK", desk: "Gas" },
  { name: "CONTI_FUTURES_USD_GAS_UK", desk: "Gas" },
  { name: "CONTI_FUTURES2_GAS_UK", desk: "Gas" },
  { name: "CONTI_FUTURES3_GAS_UK", desk: "Gas" },
  { name: "CONTI_FWD_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_BEDE_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_BENL_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_CHDE_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_FRBE_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_FRCH_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_FRDE_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_FRES_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_FRIT_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_ITCH_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_UKBE_PWR_UK", desk: "Power" },
  { name: "CONTI_IC_UKNL_PWR_UK", desk: "Power" },
  { name: "CONTI_INDEX_MGT_GAS_UK", desk: "Gas" },
  { name: "CONTI_PROD_GAS_UK", desk: "Gas" },
  { name: "CONTI_PROP_GAS_UK", desk: "Gas" },
  { name: "CONTI_SPARK_PWR_UK", desk: "Power" },
  { name: "CONTI_SPREADS_GAS_UK", desk: "Gas" },
  { name: "CONTI_SPREADS_PWR_UK", desk: "Power" },
  { name: "CONTI_STRUCTURED_PWR_UK", desk: "Power" },
  { name: "CORY_EMGEN_PWR_UK", desk: "Power" },
  { name: "CROSS_COMMODITY_PWR_UK", desk: "Power" },
  { name: "CRUDE_CH", desk: "OIL" },
  { name: "CRUDE_DELTA_CH", desk: "OIL" },
  { name: "CRUDE_PAPER_CH", desk: "OIL" },
  { name: "CRUDE_PHY_HEDGE_SG", desk: "OIL" },
  { name: "CRUDE_PHY_OPTIMISATION_SG", desk: "OIL" },
  { name: "CRUDE_SBC_OPTIMISATION_SG", desk: "OIL" },
  { name: "CRUDE_SPEC_SG", desk: "OIL" },
  { name: "CZECH_2_STOR_GAS_UK", desk: "Gas" },
  { name: "CZECH_3_STOR_GAS_UK", desk: "Gas" },
  { name: "CZECH_STOR_GAS_UK", desk: "Gas" },
  { name: "DA_INDEX_MAN_GAS_UK", desk: "Gas" },
  { name: "DE_CZ_PWR_UK", desk: "Power" },
  { name: "DE_FR_PWR_UK", desk: "Power" },
  { name: "DE_NL_PWR_UK", desk: "Power" },
  { name: "DE_PROMPT_PWR_UK", desk: "Power" },
  { name: "DE_PWR_UK", desk: "Power" },
  { name: "DE_RETL_FH_PWR_UK", desk: "Power" },
  { name: "DE_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "DE_UKR_PWR_UK", desk: "Power" },
  { name: "DERIV_WINGAS_PS_GAS_UK", desk: "Gas" },
  { name: "DIGITAL_PROFITSHARE1_PWR_UK", desk: "Power" },
  { name: "DIGITAL_PROFITSHARE2_PWR_UK", desk: "Power" },
  { name: "DIGITAL_PROFITSHARE3_PWR_UK", desk: "Power" },
  { name: "DNK_REGAS_COSTS_2023_SMT", desk: "LNG" },
  { name: "DNK_REGAS_COSTS_2024_SMT", desk: "LNG" },
  { name: "DNK_REGAS_COSTS_2025_SMT", desk: "LNG" },
  { name: "DNK_REGAS_COSTS_2026_SMT", desk: "LNG" },
  { name: "DNK_REGAS_COSTS_LNG_2023_SLNG", desk: "LNG" },
  { name: "DNK_REGAS_COSTS_LNG_2024_SLNG", desk: "LNG" },
  { name: "DNK_REGAS_COSTS_LNG_2025_SLNG", desk: "LNG" },
  { name: "DNK_REGAS_COSTS_LNG_2026_SLNG", desk: "LNG" },
  { name: "DNK_REGAS_JV_2023_SMT", desk: "LNG" },
  { name: "DNK_REGAS_JV_2024_SMT", desk: "LNG" },
  { name: "DNK_REGAS_JV_LNG_2023_SLNG", desk: "LNG" },
  { name: "DUAL_DEAL_MANAGEMENT_GAS_UK", desk: "Gas" },
  { name: "DUMMY_BAL_FLOW_GAS_UK", desk: "Gas" },
  { name: "DUMMY_EXPO_GAS_UK", desk: "Gas" },
  { name: "DUMMY_FLOW_CARBON_PWR_SG", desk: "Carbon" },
  { name: "DUMMY_FLOW_CARBON_PWR_UK", desk: "Carbon" },
  { name: "DUMMY_FLOW_GAS_DE", desk: "Gas" },
  { name: "DUMMY_FLOW_GAS_UK", desk: "Gas" },
  { name: "DUMMY_LNG_HA_UNIT_TRADE_SG", desk: "LNG" },
  { name: "DUTCH_RETAIL_GAS_UK", desk: "Gas" },
  { name: "DUTCH_SPARKS_PWR_UK", desk: "Power" },
  { name: "EC_STRAT_PWR_UK", desk: "Power" },
  { name: "EE_FLOW_PWR_UK", desk: "Power" },
  { name: "EPG_AGENT_STOR_GAS_UK", desk: "Gas" },
  { name: "EQUITY_SUPPLY_FIX_GAS_DE", desk: "Gas" },
  { name: "EQUITY_SUPPLY_FIXOIL_GAS_DE", desk: "Gas" },
  { name: "EQUITY_SUPPLY_FLEX_GAS_DE", desk: "Gas" },
  { name: "EQUITY_SUPPLY_FLEX_OIL_GAS_DE", desk: "Gas" },
  { name: "ETZEL_OPT_GAS_UK", desk: "Gas" },
  { name: "ETZEL_V_STOR_GAS_UK", desk: "Gas" },
  { name: "EU_CLEAN_SPARKS_PWR_UK", desk: "Power" },
  { name: "EU_DIRTY_SPARKS_PWR_UK", desk: "Power" },
  { name: "EU_UK_CROSS_COMM_PWR_UK", desk: "Power" },
  { name: "EUA_OPTIONS_CB_UK", desk: "Carbon" },
  { name: "EUA_OPTIONS_PWR_UK", desk: "Power" },
  { name: "EUA_TECHNICAL_PWR_UK", desk: "Carbon" },
  { name: "EUA_TRADING_PWR_UK", desk: "Carbon" },
  { name: "EUR_DEAL2", desk: "Gas" },
  { name: "EUR_SPDS_SHRT_PWR_UK", desk: "Power" },
  { name: "EURO_DEAL_MGT1_GAS_UK", desk: "Gas" },
  { name: "EURO_DEAL_MGT2_GAS_UK", desk: "Gas" },
  { name: "EURO_DEAL_MGT3_GAS_UK", desk: "Gas" },
  { name: "EURO_DEAL_MGT4_GAS_UK", desk: "Gas" },
  { name: "EURO_DEAL_MGT5_GAS_UK", desk: "Gas" },
  { name: "EURO_DEAL_MGT6_GAS_UK", desk: "Gas" },
  { name: "EURO_DEAL_MGT7_GAS_UK", desk: "Gas" },
  { name: "EURO_DEAL_MGT8_GAS_UK", desk: "Gas" },
  { name: "EURO_PWR_UK", desk: "Power" },
  { name: "EURO_SPARK_PROP_GAS_UK", desk: "Gas" },
  { name: "EURO_SPREAD_MGT_GAS_UK", desk: "Gas" },
  { name: "EURO_SPREADS_PWR_UK", desk: "Power" },
  { name: "EX_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "EXXON_DEAL_MGT_GAS_UK", desk: "Gas" },
  { name: "FD_CROSS_COMM_PWR_UK", desk: "Power" },
  { name: "FIN_OPT_GGLNG", desk: "LNG" },
  { name: "FINANCIAL_GAS_UK", desk: "Gas" },
  { name: "FINOPT_PORTFOLIO_GGLNG", desk: "LNG" },
  { name: "FINOPT2_PORTFOLIO_GGLNG", desk: "LNG" },
  { name: "FLOWMGT_DGTL_UK", desk: "Power" },
  { name: "FR_PORT_GAS_UK", desk: "Gas" },
  { name: "FR_PWR_UK", desk: "Power" },
  { name: "FR_RE_FIXED_2_GAS_UK", desk: "Gas" },
  { name: "FR_RE_FIXED_GAS_UK", desk: "Gas" },
  { name: "FR_RE_GAS_INDEX_GAS_UK", desk: "Gas" },
  { name: "FR_RE_OIL_INDEX_GAS_UK", desk: "Gas" },
  { name: "FR_RE_OIL_UK", desk: "Gas" },
  { name: "FR_RE_STOR_GAS_UK", desk: "Gas" },
  { name: "FR_RET_CAPACITY_GAS_UK", desk: "Gas" },
  { name: "FR_RET_FIXED_GAS_UK", desk: "Gas" },
  { name: "FR_RET_FLEX_DA_GAS_UK", desk: "Gas" },
  { name: "FR_RET_FLEX_INDEX_GAS_UK", desk: "Gas" },
  { name: "FR_RET_INDEX_GAS_UK", desk: "Gas" },
  { name: "FR_RET_LIGHTSHIP_GAS_UK", desk: "Gas" },
  { name: "FR_RET_LIGHTSHIP_INDEX_GAS_UK", desk: "Gas" },
  { name: "FR_RET_OIL_INDEX_GAS_UK", desk: "Gas" },
  { name: "FR_RET_OPEN_GAS_UK", desk: "Gas" },
  { name: "FR_RET_WE_BAL_GAS_UK", desk: "Gas" },
  { name: "FR_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "FR_UK_PWR_UK", desk: "Power" },
  { name: "FR_UK2_PWR_UK", desk: "Power" },
  { name: "FR_UK3_PWR_UK", desk: "Power" },
  { name: "FUEL_OIL_CH", desk: "OIL" },
  { name: "FULCRUM_EXECUTION_PWR_UK", desk: "Power" },
  { name: "FULCRUM_OPT_PWR_UK", desk: "Power" },
  { name: "FULCRUM_TRIAD_PWR_UK", desk: "Power" },
  { name: "FUTURES_GAS_UK", desk: "Gas" },
  { name: "FUTURES_USD_GAS_UK", desk: "Gas" },
  { name: "FX_AUTO1_DGTL_UK", desk: "Power" },
  { name: "FX_AUTO2_DGTL_UK", desk: "Power" },
  { name: "FX_AUTO3_DGTL_UK", desk: "Power" },
  { name: "FX_AUTOBALANCING_DGTL_UK", desk: "Power" },
  { name: "FX_HDG_LNG_UK", desk: "FX" },
  { name: "FX_TERM_GAS_UK", desk: "Gas" },
  { name: "GAS_1_DGTL_UK", desk: "Gas" },
  { name: "GAS_2_DGTL_UK", desk: "Power" },
  { name: "GAS_3_DGTL_UK", desk: "Power" },
  { name: "GAS_4_DGTL_UK", desk: "Power" },
  { name: "GAS_5_DGTL_UK", desk: "Power" },
  { name: "GAS_6_DGTL_UK", desk: "Power" },
  { name: "GAS_COND_CH", desk: "OIL" },
  { name: "GAS_FX_ROLL_GAS_UK", desk: "Gas" },
  { name: "GAS_HEDGING_OIL_UK", desk: "OIL" },
  { name: "GAS_TF1_DGTL_UK", desk: "Gas" },
  { name: "GASLN_COMP_STORAGE_CH", desk: "OIL" },
  { name: "GASOLINE_CH", desk: "OIL" },
  { name: "GASTERRA_STOR_GAS_UK", desk: "Gas" },
  { name: "GLOBAL_GAS_PROP_GAS_UK", desk: "Gas" },
  { name: "GLOBAL_SPREAD_MGMT_GAS_UK", desk: "Gas" },
  { name: "GLOBAL_SPREAD_MGMT2_GAS_UK", desk: "Gas" },
  { name: "GOO_PWR_UK", desk: "Power" },
  { name: "GPL_B_STOR_GAS_UK", desk: "Gas" },
  { name: "GPL_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "GPL_S_STORSWING_GAS_UK", desk: "Gas" },
  { name: "GPL2_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "GPLL_B_STOR_GAS_UK", desk: "Gas" },
  { name: "GPLL_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "GTF_B_STOR_GAS_UK", desk: "Gas" },
  { name: "HAIDACH_STOR_GAS_DE", desk: "Gas" },
  { name: "HEDGE_STOR_GAS_UK", desk: "Gas" },
  { name: "HEDGE_STORAGE_GAS_UK", desk: "Gas" },
  { name: "HEDGING_FLEX_GAS_DE", desk: "Gas" },
  { name: "HEDGING_GAS_DE", desk: "Gas" },
  { name: "HEDGING_MOD_GAS_DE", desk: "Gas" },
  { name: "HH_DEAL_MGMT_GAS_UK", desk: "Gas" },
  { name: "HU_RO_PWR_UK", desk: "Power" },
  { name: "HU_STOR_GAS_UK", desk: "Gas" },
  { name: "HUMBLY_STOR_GAS_UK", desk: "Gas" },
  { name: "INDEX_MANAGEMENT_GAS_UK", desk: "Gas" },
  { name: "INDEX_SPB_GAS_UK", desk: "Gas" },
  { name: "INDEX_SWING_GAS_UK", desk: "Gas" },
  { name: "INTDY_IC_FRUK_PWR_UK", desk: "Power" },
  { name: "INTDY_IC_NLDE_PWR_UK", desk: "Power" },
  { name: "INTDY_IC_UKNL_PWR_UK", desk: "Power" },
  { name: "INTEGRAL_FX_UK", desk: "FX" },
  { name: "INTERNAL_SWING_GAS_UK", desk: "Gas" },
  { name: "INTRADAY_4_PWR_UK", desk: "Power" },
  { name: "INTRADAY_BE_PWR_UK", desk: "Power" },
  { name: "INTRADAY_CH_PWR_UK", desk: "Power" },
  { name: "INTRADAY_DE_PWR_UK", desk: "Power" },
  { name: "INTRADAY_ES_PWR_UK", desk: "Power" },
  { name: "INTRADAY_FR_PWR_UK", desk: "Power" },
  { name: "INTRADAY_JOINTVENTURE_2_PWR_UK", desk: "Power" },
  { name: "INTRADAY_NL_PWR_UK", desk: "Power" },
  { name: "INTRADAY_PWR_UK", desk: "Power" },
  { name: "INTRADAY_SYSTEMATIC_1_PWR_UK", desk: "Power" },
  { name: "INTRADAY_SYSTEMATIC_2_PWR_UK", desk: "Power" },
  { name: "INTRADAY_SYSTEMATIC_5_PWR_UK", desk: "Power" },
  { name: "INTRADAY_SYSTEMATIC_PWR_UK", desk: "Power" },
  { name: "INTRADAY_UK_PWR_UK", desk: "Power" },
  { name: "ITALIAN_CLEAN_SPARKS_PWR_UK", desk: "Power" },
  { name: "IUK_INVENTORY_GAS_UK", desk: "Gas" },
  { name: "JCC_DERIVATIVES_2019_LNG_SG", desk: "LNG" },
  { name: "JCC_DERIVATIVES_2020_LNG_SG", desk: "LNG" },
  { name: "JCC_DERIVATIVES_2021_LNG_SG", desk: "LNG" },
  { name: "JCC_DERIVATIVES_2022_LNG_SG", desk: "LNG" },
  { name: "JCC_DERIVATIVES_2023_LNG_SG", desk: "LNG" },
  { name: "JCC_DERIVATIVES_LNG_SG", desk: "LNG" },
  { name: "JCC_DERIVATIVES_LNG_UK", desk: "LNG" },
  { name: "JEMGUM_STOR_GAS_DE", desk: "Gas" },
  { name: "LCAL_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "LEC_TRANS_PWR_UK", desk: "Power" },
  { name: "LEG_SALES_DEMAND_DA_IDX_GAS_DE", desk: "Gas" },
  { name: "LEG_SALES_DEMAND_FIXED_GAS_DE", desk: "Gas" },
  { name: "LEG_SALES_DEMAND_FLEX_GAS_DE", desk: "Gas" },
  { name: "LEG_SALES_DEMAND_MA_IDX_GAS_DE", desk: "Gas" },
  { name: "LEG_SALES_DEMAND_MAV_IDX_GAS_DE", desk: "Gas" },
  { name: "LEG_SALES_DEMAND_OIL_IDX_GAS_DE", desk: "Gas" },
  { name: "LEG_SALES_DEMAND_SIGMOID_GAS_DE", desk: "Gas" },
  { name: "LEG_SALES_DEMAND_WGCE_GAS_DE", desk: "Gas" },
  { name: "LEG_SALES_DEMAND_YA_IDX_GAS_DE", desk: "Gas" },
  { name: "LIGHT_ENDS_CH", desk: "OIL" },
  { name: "LNG_DEAL_MGT_GAS_UK", desk: "LNG" },
  { name: "LNG_DERIVS_GAS_UK", desk: "Gas" },
  { name: "LNG_DERIVS_MGT_GAS_UK", desk: "LNG" },
  { name: "LNG_DESK_PS_SMT", desk: "LNG" },
  { name: "LNG_DESK_PS_SMTS", desk: "LNG" },
  { name: "LNG_EXCH_SWAPS_GAS_UK", desk: "Gas" },
  { name: "LNG_FIN_HEDGE_GGLNG", desk: "LNG" },
  { name: "LNG_FIN_HEDGE_SG", desk: "LNG" },
  { name: "LNG_FIN_SPEC_GGLNG", desk: "LNG" },
  { name: "LNG_HA_2022_GGLNG", desk: "LNG" },
  { name: "LNG_HA_2022_SG", desk: "LNG" },
  { name: "LNG_HA_2023_GGLNG", desk: "LNG" },
  { name: "LNG_HA_2023_SG", desk: "LNG" },
  { name: "LNG_HA_UNIT_TRADE_SG", desk: "LNG" },
  { name: "LNG_HEDGE_GAS_UK", desk: "Gas" },
  { name: "LNG_HEDGING_OIL_UK", desk: "OIL" },
  { name: "LNG_IN_TANK_GAS_UK", desk: "Gas" },
  { name: "LNG_PHYS_NONSEIC_GGLNG", desk: "OIL" },
  { name: "LNG_PHYS_SEIC_GGLNG", desk: "LNG" },
  { name: "LNG_PHYS_SEIC_SG", desk: "OIL" },
  { name: "LNG_PHYSICAL_OPTION_HEDGING_SMTS", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2018_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2018_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2019_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2019_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2020_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2020_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2021_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2021_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2022_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2022_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2023_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2023_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2024_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2024_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2025_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2025_SLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2026_SG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_2026_SLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_FREIGHT_FFA_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_GGLNG", desk: "LNG" },
  { name: "LNG_PORTFOLIO_SG", desk: "LNG" },
  { name: "LNG_SWAPS_GAS_UK", desk: "Gas" },
  { name: "LPG_PROFITSHARE_SG", desk: "OIL" },
  { name: "LPG_PROFITSHARE_UK", desk: "OIL" },
  { name: "MANAGEMENT_EP_UK", desk: "Power" },
  { name: "MANAGEMENT_FEES_LNG_SG", desk: "LNG" },
  { name: "MANAGEMENT_FX_X-DESK_UK", desk: "FX" },
  { name: "MANAGEMENT_GAIL_DOP_2023_SG", desk: "LNG" },
  { name: "MANAGEMENT_GAS_UK", desk: "Gas" },
  { name: "MANAGEMENT_GPE_GAS_UK", desk: "Gas" },
  { name: "MANAGEMENT_LNG_GGLNG", desk: "LNG" },
  { name: "MANAGEMENT_LNG_SG", desk: "LNG" },
  { name: "MANAGEMENT_POSITIONS_2_GAS_UK", desk: "Gas" },
  { name: "MANAGEMENT_POSITIONS_GAS_UK", desk: "Gas" },
  { name: "MANAGEMENT_PWR_UK", desk: "Power" },
  { name: "MANAGEMENT_X-DESK_UK", desk: "Gas" },
  { name: "MED_TERM_EURO_PWR_UK", desk: "Power" },
  { name: "MEDIT_PWR_UK", desk: "Power" },
  { name: "MGMT_CREDIT_GAS_UK", desk: "Gas" },
  { name: "MGMT_LNG_MARKET_ACCESS_GGLNG", desk: "LNG" },
  { name: "MGMT_LNG_MARKET_ACCESS_SG", desk: "LNG" },
  { name: "MGMT_RESERVES_GAS_UK", desk: "Gas" },
  { name: "MID_DISTILLATES_CH", desk: "OIL" },
  { name: "MIDWEST_GAS_US", desk: "Gas" },
  { name: "MOA_HEDGE_GAS_DE", desk: "Gas" },
  { name: "MOD_DEALFLOW_GAS_UK", desk: "Gas" },
  { name: "MOD_IDXMGMT_GAS_UK", desk: "Gas" },
  { name: "MODEL_TRADING_PWR_UK", desk: "Power" },
  { name: "MULTI_CROSS_COMM_PWR_UK", desk: "Power" },
  { name: "NAFTA_4_STOR_GAS_UK", desk: "Gas" },
  { name: "NAFTA_A_STOR_GAS_UK", desk: "Gas" },
  { name: "NAFTA_CHRIS_STOR_GAS_UK", desk: "Gas" },
  { name: "NAFTA_CROSS_STOR_GAS_UK", desk: "Gas" },
  { name: "NAFTA_HEDGE_2_STOR_GAS_UK", desk: "Gas" },
  { name: "NAFTA_HEDGE_3_STOR_GAS_UK", desk: "Gas" },
  { name: "NAFTA_HEDGE_STOR_GAS_UK", desk: "Gas" },
  { name: "NAFTA_REV_2_B_STOR_GAS_UK", desk: "Gas" },
  { name: "NAFTA_REV_B_STOR_GAS_UK", desk: "Gas" },
  { name: "NAPHTHA_CH", desk: "OIL" },
  { name: "NAPHTHA_PHY_HEDGE_SG", desk: "OIL" },
  { name: "NAPHTHA_SPEC_SG", desk: "OIL" },
  { name: "NBP_B_STOR_GAS_UK", desk: "Gas" },
  { name: "NBP_BOOK_BAL_GAS_UK", desk: "Gas" },
  { name: "NBP_DEAL_MGT_GAS_UK", desk: "Gas" },
  { name: "NBP_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "NBP_S_STOR_GAS_UK", desk: "Gas" },
  { name: "NCG_B_STOR_GAS_UK", desk: "Gas" },
  { name: "NCG_B_SWAP_STOR_GAS_UK", desk: "Gas" },
  { name: "NCG_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "NCG_S_STOR_GAS_UK", desk: "Gas" },
  { name: "NCG_STOR_GAS_UK", desk: "Gas" },
  { name: "NCG_WD_BAL_STOR_GAS_UK", desk: "Gas" },
  { name: "NCGGPL_B_STOR_GAS_UK", desk: "Gas" },
  { name: "NL_DE_RETAIL_HEDGES_PWR_UK", desk: "Power" },
  { name: "NL_RE_FIXED_GAS_UK", desk: "Gas" },
  { name: "NL_RETAIL_DEEMED_DEMAND_POWER_UK", desk: "Power" },
  { name: "NL_RETAIL_HEDGE_POWER_UK", desk: "Power" },
  { name: "NL_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "NL_UK2_PWR_UK", desk: "Power" },
  { name: "NORDSTREAM_PS_GAS_UK", desk: "Gas" },
  { name: "NUTTER_STOR_GAS_DE", desk: "Gas" },
  { name: "OIL_2020_LNG_SG", desk: "OIL" },
  { name: "Oil_2021_LNG_SG", desk: "OIL" },
  { name: "OIL_2022_LNG_SG", desk: "OIL" },
  { name: "OIL_2023_LNG_SG", desk: "OIL" },
  { name: "OIL_DERIVATIVES_GAS_UK", desk: "OIL" },
  { name: "OIL_EXCH_GAS_UK", desk: "OIL" },
  { name: "OIL_SPREADS_GAS_UK", desk: "Gas" },
  { name: "OIL_SPREADS2_GAS_UK", desk: "Gas" },
  { name: "OIL_SPREADS3_GAS_UK", desk: "Gas" },
  { name: "OPEN_2_STOR_GAS_UK", desk: "Gas" },
  { name: "OPEN_3_STOR_GAS_UK", desk: "Gas" },
  { name: "OPEN_4_STOR_GAS_UK", desk: "Gas" },
  { name: "OPEN_STORAGE_GAS_UK", desk: "Gas" },
  { name: "OPEN_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "OPS_PROMPT_PWR_UK", desk: "Power" },
  { name: "OPS_PWR_UK", desk: "Power" },
  { name: "OPS_UK_PWR_UK", desk: "Power" },
  { name: "ORIG_PROP_EP_UK", desk: "Power" },
  { name: "OS_PORT_FIXED_3_GAS_UK", desk: "Gas" },
  { name: "OS_PORT_FIXED_4_GAS_UK", desk: "Gas" },
  { name: "OS_PORTFOLIO_1_GAS_UK", desk: "Gas" },
  { name: "OS_PORTFOLIO_2_GAS_UK", desk: "Gas" },
  { name: "OS_PORTFOLIO_3_GAS_UK", desk: "Gas" },
  { name: "OS_PORTFOLIO_4_GAS_UK", desk: "Gas" },
  { name: "OS_SWING_GAS_UK", desk: "Gas" },
  { name: "OUTRIGHT_FX_SG", desk: "FX" },
  { name: "OUTRIGHT_FX_UK", desk: "FX" },
  { name: "OUTRIGHT_LPG_SG", desk: "FX" },
  { name: "OUTRIGHT_LPGSPEC_SG", desk: "FX" },
  { name: "OUTRIGHT_OIL_SG", desk: "FX" },
  { name: "PEAKER_OPT_PWR_UK", desk: "Power" },
  { name: "PEGN_S_SWAP_STOR_GAS_UK", desk: "Gas" },
  { name: "PEGNORD_B_MAN_STOR_GAS_UK", desk: "Gas" },
  { name: "PEGNORD_B_STOR_GAS_UK", desk: "Gas" },
  { name: "PEGNORD_S_STOR_GAS_UK", desk: "Gas" },
  { name: "PEGSUD_B_STOR_GAS_UK", desk: "Gas" },
  { name: "PHYS_HEDGING_OIL_UK", desk: "OIL" },
  { name: "PHYSICAL_GAS_US", desk: "Gas" },
  { name: "PHYSICAL_LPG_SG", desk: "OIL" },
  { name: "PORT_BALANCING_GAS_UK", desk: "Gas" },
  { name: "PORT_BASIS_GAS_UK", desk: "Gas" },
  { name: "PORT_BUNDLE_HEDGE_GAS_UK", desk: "Gas" },
  { name: "PORT_BUNDLE_PROXY_GAS_UK", desk: "Gas" },
  { name: "PORT_BUNDLE_STOR_GAS_UK", desk: "Gas" },
  { name: "PORT_CAPACITY_GAS_UK", desk: "Gas" },
  { name: "PORT_EQUITY_STOR_GAS_UK", desk: "Gas" },
  { name: "PORT_EUROHEDGE_GAS_UK", desk: "Gas" },
  { name: "PORT_GAS_UK", desk: "Gas" },
  { name: "PORT_GPE_GAS_UK", desk: "Gas" },
  { name: "PORT_LOGISTICS_GAS_UK", desk: "Gas" },
  { name: "PORT_MARKET_ROUTE_GAS_UK", desk: "Gas" },
  { name: "PORT_NAFTA_9_STOR_GAS_UK", desk: "Gas" },
  { name: "PORT_NAFTA_GAS_UK", desk: "Gas" },
  { name: "PORT_OIL_GAS_UK", desk: "OIL" },
  { name: "PORT_OPTIMISATION_GAS_UK", desk: "Gas" },
  { name: "PORT_SPB_GAS_UK", desk: "Gas" },
  { name: "PORT_STOR_GAS_UK", desk: "Gas" },
  { name: "PORT_TRANSPORT_GAS_UK", desk: "Gas" },
  { name: "PORT_WINGAS_PS_GAS_UK", desk: "Gas" },
  { name: "PORTFOLIO_GAS_CH", desk: "Gas" },
  { name: "PORTFOLIO_OIL_UK", desk: "FX" },
  { name: "PORTFOLIO_OPTIONS_GAS_UK", desk: "Gas" },
  { name: "POWER_DERIVATIVES_GAS_UK", desk: "Power" },
  { name: "POWER_FLOW_OPTIONS_GAS_UK", desk: "Power" },
  { name: "POWER_OPTIONS_PWR_UK", desk: "Power" },
  { name: "POWER_PROP_OPTIONS_GAS_UK", desk: "Power" },
  { name: "POZAGAS_STOR_GAS_UK", desk: "Gas" },
  { name: "PP_MANAGEMENT_GAS_UK", desk: "Gas" },
  { name: "PRIME_EMGEN_PWR_UK", desk: "Power" },
  { name: "PROJECTS_EP_UK", desk: "Power" },
  { name: "PROP_10_GAS_UK", desk: "Gas" },
  { name: "PROP_11_GAS_UK", desk: "Gas" },
  { name: "PROP_12_GAS_UK", desk: "Gas" },
  { name: "PROP_13_GAS_UK", desk: "Gas" },
  { name: "PROP_14_GAS_UK", desk: "Gas" },
  { name: "PROP_15_GAS_UK", desk: "Gas" },
  { name: "PROP_2_GAS_UK", desk: "Gas" },
  { name: "PROP_3_GAS_UK", desk: "Gas" },
  { name: "PROP_4_GAS_UK", desk: "Gas" },
  { name: "PROP_5_GAS_UK", desk: "Gas" },
  { name: "PROP_7_GAS_UK", desk: "Gas" },
  { name: "PROP_8_GAS_UK", desk: "Gas" },
  { name: "PROP_9_GAS_UK", desk: "Gas" },
  { name: "PROP_FX_UK", desk: "FX" },
  { name: "PROP_FX_US", desk: "FX" },
  { name: "PROP_OPTIONS_2_GAS_UK", desk: "Gas" },
  { name: "PROP_OPTIONS_3_GAS_UK", desk: "Gas" },
  { name: "PROP_OPTIONS_GAS_UK", desk: "Gas" },
  { name: "PROP_US_FX_UK", desk: "FX" },
  { name: "PROXY_SWING_GAS_UK", desk: "Gas" },
  { name: "PSV_STOR_GAS_UK", desk: "Gas" },
  { name: "PWR_1_DGTL_UK", desk: "Power" },
  { name: "PWR_2_DGTL_UK", desk: "Power" },
  { name: "PWR_3_DGTL_UK", desk: "Power" },
  { name: "PWR_4_DGTL_UK", desk: "Power" },
  { name: "PWR_5_DGTL_UK", desk: "Power" },
  { name: "PWR_FXROLL_PWR_UK", desk: "Power" },
  { name: "QUANT_FX_GAS_UK", desk: "Gas" },
  { name: "RE_MR1_GAS_UK", desk: "Gas" },
  { name: "RE_TF1_GAS_UK", desk: "Gas" },
  { name: "RE_TF2_GAS_UK", desk: "Gas" },
  { name: "REGAS_BE_GAS_UK", desk: "LNG" },
  { name: "REGAS_DET_2024_GAS_UK", desk: "LNG" },
  { name: "REGAS_DET_COSTS_2024_GAS_UK", desk: "LNG" },
  { name: "REGAS_FOS_GAS_UK", desk: "LNG" },
  { name: "REGAS_FR_2021_GAS_UK", desk: "LNG" },
  { name: "REGAS_FR_GAS_UK", desk: "LNG" },
  { name: "REGAS_GERMANY_COSTS_2024_SLNG", desk: "LNG" },
  { name: "REGAS_SPAIN_2024_GAS_UK", desk: "LNG" },
  { name: "REGOS_PWR_UK", desk: "Power" },
  { name: "REHDEN_STOR_GAS_DE", desk: "Gas" },
  { name: "RGGO_PWR_UK", desk: "Power" },
  { name: "ROC_PWR_UK", desk: "Power" },
  { name: "ROUGH_STOR_GAS_UK", desk: "Gas" },
  { name: "SALES_DEMAND_DA_INDEX_GAS_DE", desk: "Gas" },
  { name: "SALES_DEMAND_FIXED_GAS_DE", desk: "Gas" },
  { name: "SALES_DEMAND_FLEX_GAS_DE", desk: "Gas" },
  { name: "SALES_DEMAND_MA_INDEX_GAS_DE", desk: "Gas" },
  { name: "SALES_DEMAND_OIL_INDEX_GAS_DE", desk: "Gas" },
  { name: "SALES_DEMAND_SIGMOID_GAS_DE", desk: "Gas" },
  { name: "SALES_DEMAND_YA_INDEX_GAS_DE", desk: "Gas" },
  { name: "SALES_GAS_UK", desk: "Gas" },
  { name: "SALES_SWING_AGG_GAS_DE", desk: "Gas" },
  { name: "SALES_SWING_GAS_DE", desk: "Gas" },
  { name: "SALES_SWING_SIG_GAS_DE", desk: "Gas" },
  { name: "SALES_SWING2_GAS_DE", desk: "Gas" },
  { name: "SEE_StratOrig_GAS_UK", desk: "Gas" },
  { name: "SHORT_TERM_DE_PWR_UK", desk: "Power" },
  { name: "SHORT_TERM_ES_PWR_UK", desk: "Power" },
  { name: "SHORT_TERM_FR_PWR_UK", desk: "Power" },
  { name: "SHORT_TERM_HU_PWR_UK", desk: "Power" },
  { name: "SHORT_TERM_UK_PWR_UK", desk: "Power" },
  { name: "SHORT_TERM_UK2_PWR_UK", desk: "Power" },
  { name: "SHORT_TERM_UK3_PWR_UK", desk: "Power" },
  { name: "SK_HU_PWR_UK", desk: "Power" },
  { name: "SMT_WIEE_PS_UK", desk: "Gas" },
  { name: "SOUTH_EAST_EUROPE_PWR_UK", desk: "Power" },
  { name: "SP_TRANS_GAS_UK", desk: "Gas" },
  { name: "SPEC_2_FX_UK", desk: "FX" },
  { name: "SPEC_FX_UK", desk: "FX" },
  { name: "SPEC_OIL_ADI_UK", desk: "OIL" },
  { name: "SPEC_OIL_ANDREW_UK", desk: "OIL" },
  { name: "SPEC_OIL_BEN_UK", desk: "OIL" },
  { name: "SPEC_OIL_GILLIAN_UK", desk: "OIL" },
  { name: "SPEC_OIL_UK", desk: "OIL" },
  { name: "SPEC_OIL_UK2", desk: "OIL" },
  { name: "SPEC_OPTIONS_PWR_UK", desk: "Power" },
  { name: "SPO_Index_DA_Gas_UK", desk: "Gas" },
  { name: "SPREADS_RV1_OIL_UK", desk: "OIL" },
  { name: "STATIC_MOD_GAS_DE", desk: "Gas" },
  { name: "STOR_OPTIONS_GAS_UK", desk: "Gas" },
  { name: "STORAGE_GAS_DE", desk: "Gas" },
  { name: "STRUC_OIL_SG", desk: "OIL" },
  { name: "STRUC_OIL_UK", desk: "OIL" },
  { name: "STRUC_OPTIONS_GAS_UK", desk: "Gas" },
  { name: "STRUC_OPTIONS_OIL_SG", desk: "OIL" },
  { name: "STRUC_OPTIONS_OIL_UK", desk: "OIL" },
  { name: "STRUCTURED_SPARKS_PWR_UK", desk: "Power" },
  { name: "SYS_CROSS_COMM_PWR_UK", desk: "Power" },
  { name: "TAQA_OPT_GAS_UK", desk: "Gas" },
  { name: "TATA_OCGT_PWR_UK", desk: "Power" },
  { name: "TATA_OPT_PWR_UK", desk: "Power" },
  { name: "TATA_TRIAD_PWR_UK", desk: "Power" },
  { name: "TEMP_FLEX_GAS_UK", desk: "Gas" },
  { name: "THE_2_STOR_GAS_UK", desk: "Gas" },
  { name: "THE_3_STOR_GAS_UK", desk: "Gas" },
  { name: "THE_4_STOR_GAS_UK", desk: "Gas" },
  { name: "THE_5_STOR_GAS_UK", desk: "Gas" },
  { name: "THE_6_STOR_GAS_UK", desk: "Gas" },
  { name: "THE_S_STOR_GAS_UK", desk: "Gas" },
  { name: "TOLLING_PWR_UK", desk: "Power" },
  { name: "TRANS_TRSY_HDG_FX_UK", desk: "FX" },
  { name: "TRANSPORTATION_GAS_DE", desk: "Gas" },
  { name: "TREND_FOLLOW_GAS_UK", desk: "Gas" },
  { name: "TRS_B_STOR_GAS_UK", desk: "Gas" },
  { name: "TRS_RE_STOR_GAS_UK", desk: "Gas" },
  { name: "TRSY_HDG_FX_CH", desk: "FX" },
  { name: "TRSY_HDG_FX_LNG", desk: "FX" },
  { name: "TRSY_HDG_FX_SG", desk: "FX" },
  { name: "TRSY_HDG_FX_UK", desk: "FX" },
  { name: "TRSY_HDG_FX_US", desk: "FX" },
  { name: "TRSY_HDG_GAS_UK", desk: "FX" },
  { name: "TRSY_HDG_PWR_UK", desk: "FX" },
  { name: "TRUE_NORTH_GAS_UK", desk: "Gas" },
  { name: "TTF_B_STOR_GAS_UK", desk: "Gas" },
  { name: "TTF_EWEG_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "TTF_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "TTF_S_3_STOR_GAS_UK", desk: "Gas" },
  { name: "TTF_S_STOR_GAS_UK", desk: "Gas" },
  { name: "TTF_S_STORSWING_GAS_UK", desk: "Gas" },
  { name: "TTF_WD_BAL_STOR_GAS_UK", desk: "Gas" },
  { name: "TTFNCG_B_STOR_GAS_UK", desk: "Gas" },
  { name: "UER_VAL_VER_EP_UK", desk: "Carbon" },
  { name: "UK_CASHOUT_PWR_UK", desk: "Power" },
  { name: "UK_CLEAN_SPARKS_PWR_UK", desk: "Power" },
  { name: "UK_CURVE_PWR_UK", desk: "Power" },
  { name: "UK_DEALFLOW_PWR_UK", desk: "Power" },
  { name: "UK_DIRTY_SPARKS_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_AGR_PEAKER_PWR", desk: "Power" },
  { name: "UK_EMGEN_ALLEN_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_AMP_PEAKER_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_AMY_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_AREVON_CMG_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_AREVON_LFG_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_BAL_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_BENEFITS_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_BUXTON_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_BYGEN_PEAKER_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_CANADIAN_SOL_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_CASHOUT_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_CASWELL_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_CAVENDISH_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_CHESTERFIELD_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_COPSE_PEAKER_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_CROUCHLAND_AD", desk: "Power" },
  { name: "UK_EMGEN_CROYDON_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_DERBY_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_ELMS_PEAKER_PWR", desk: "Power" },
  { name: "UK_EMGEN_ENCAVIS_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_EXETER_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_FINWAY_PEAKER", desk: "Power" },
  { name: "UK_EMGEN_FIXPRICE_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_HALL_FARM_PEAKER", desk: "Power" },
  { name: "UK_EMGEN_HEARTLANDS_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_HOOTON_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INF_HEM_HEATH_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INF_STAVELEY_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_GAS_B_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_GAS_C_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_GAS_D_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_GAS_E_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_GAS_F_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_GAS_G_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_GAS_H_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_GAS_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_LFG_PWR", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_PEAKER", desk: "Power" },
  { name: "UK_EMGEN_INFINIS_PROPANE", desk: "Power" },
  { name: "UK_EMGEN_INTRADAY_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_KLL_HYDRO_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_LILLYHALL_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_NEWTON_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_NSTREAM_CASHOUT_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_PYEBRIDGE_PEAKER", desk: "Power" },
  { name: "UK_EMGEN_QUINBROOK_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_REDDITCH_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_ROLLSROYCE_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_SHAPE_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_SHOTTON_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_STATERA_PEAKER_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_TEM_CASHOUT_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_THORNHILL_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_UKPR_PEAKER_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_VENTURE_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_VIKING_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_WALKER_BAL_PWR_UK", desk: "Power" },
  { name: "UK_EMGEN_WALKER_CAR_PEAKER_PWR", desk: "Power" },
  { name: "UK_EMGEN_WALKER_PEAKER", desk: "Power" },
  { name: "UK_EMGEN_WATERS_PWR_UK", desk: "Power" },
  { name: "UK_GAS_FLEX_GAS_UK", desk: "Gas" },
  { name: "UK_GAS_FLEX_INDEX_GAS_UK", desk: "Gas" },
  { name: "UK_IMBALANCE_PWR_UK", desk: "Power" },
  { name: "UK_OPEN_RETAIL_GAS_UK", desk: "Gas" },
  { name: "UK_PROD_GAS_UK", desk: "Gas" },
  { name: "UK_PROMPT_BAL_GAS_UK", desk: "Gas" },
  { name: "UK_Prompt_PWR_UK", desk: "Power" },
  { name: "UK_RE_ARMAD_GAS_UK", desk: "Gas" },
  { name: "UK_RE_FIXED_GAS_UK", desk: "Gas" },
  { name: "UK_RETAIL_BAL_PWR_UK", desk: "Power" },
  { name: "UK_RETAIL_DEEMED_GAS_UK", desk: "Gas" },
  { name: "UK_RETAIL_EG_UK", desk: "Power" },
  { name: "UK_RETAIL_FIXED_GAS_UK", desk: "Gas" },
  { name: "UK_RETAIL_FLEX_GAS_UK", desk: "Gas" },
  { name: "UK_RETAIL_FLEX_ICESETTLE_GAS_UK", desk: "Gas" },
  { name: "UK_RETAIL_FLEX_INDEX_GAS_UK", desk: "Gas" },
  { name: "UK_RETAIL_OOC_GAS_UK", desk: "Gas" },
  { name: "UK_RETAIL_PROP_1", desk: "Gas" },
  { name: "UK_RETAIL_WD_BAL_GAS_UK", desk: "Gas" },
  { name: "UK_RETAIL_WD_WINGAS_GAS_UK", desk: "Gas" },
  { name: "UK_ST_SPARKS_PWR_UK", desk: "Power" },
  { name: "UK_STRUCTURED_FLOW_PWR_UK", desk: "Power" },
  { name: "UK-NL_PWR_UK", desk: "Power" },
  { name: "UKR_STOR_GAS_UK", desk: "Gas" },
  { name: "US_1_DGTL_UK", desk: "Power" },
  { name: "US_2_DGTL_UK", desk: "Power" },
  { name: "US_3_DGTL_UK", desk: "Power" },
  { name: "USBAL_DGTL_UK", desk: "Gas" },
  { name: "USGAS_2022_GGLNG", desk: "LNG" },
  { name: "USGAS_2023_GGLNG", desk: "LNG" },
  { name: "VCU_DEALFLOW_EP_UK", desk: "Power" },
  { name: "VIRTUAL_TRAN_GAS_UK", desk: "Gas" },
  { name: "VITOL_SUSP_GAS_UK", desk: "Gas" },
  { name: "VITOL_SUSP_PWR_UK", desk: "Power" },
  { name: "VTP_PS_2_STOR_GAS_UK", desk: "Gas" },
  { name: "VTP_PS_2A_STOR_GAS_UK", desk: "Gas" },
  { name: "WIN_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "WINGAS_DEAL_MGT_GAS_UK", desk: "Gas" },
  { name: "WTD_STORAGE_GAS_UK", desk: "Gas" },
  { name: "YARA_RE_GAS_UK", desk: "Gas" },
  { name: "ZTP_B_STOR_GAS_UK", desk: "Gas" },
  { name: "ZTP_WD_BAL_STOR_GAS_UK", desk: "Gas" },
  { name: "ZTP_WD_BALANCING_GAS_UK", desk: "Gas" },
  { name: "REGAS_SPAIN_2025_GAS_UK", desk: "LNG" },
  { name: "DNK_REGAS_2025_SMT", desk: "LNG" },
  { name: "UNIPER_ET_GAS_UK", desk: "Gas" },
  { name: "LNG_FO_GAIL_RNST_26_SLNG", desk: "LNG" },
  { name: "PROP_18_SMT", desk: "Gas" },
  { name: "LNG_FIN_SPEC_SYST2_SLNG", desk: "LNG" },
  { name: "PORT_BAL_GAS_UK", desk: "Gas" },
  { name: "VTP_PS_3_STOR_GAS_UK", desk: "Gas" },
  { name: "VTP_PS_STOR_GAS_UK", desk: "Gas" },
  { name: "GAS_STRATPOSITION_SMT", desk: "Gas" },
  { name: "OIL_TRADING_STRAT_SMT", desk: "OIL" },
  { name: "NBP_2_STOR_GAS_UK", desk: "Gas" },
  { name: "PROJECTS_EP_UK_CARBON", desk: "Carbon" },
  { name: "LNG_FO_GAIL_UQT_26_SLNG", desk: "LNG" },
  { name: "GAS_8_DGTL_SMT", desk: "Gas" },
  { name: "EE_GAS_FLOW_SMT", desk: "Gas" },
  { name: "LNG_PORTFOLIO_2028_SG", desk: "LNG" },
  { name: "SOCAR_BASE_SMT", desk: "Gas" },
  { name: "METAL_DESK_PS_SMT", desk: "Metal" },
  { name: "METAL_DESK_PS_SMTS", desk: "Metal" },
  { name: "CONOCO_DEAL_MANAGEMENT_GAS_UK", desk: "Gas" },
  { name: "PROP_6_GAS_UK", desk: "Gas" },
];

// Generate sign-offs for retired books (all signed)
const generateRetiredSignOffs = (): SignOffRecord[] => {
  return workingDays.map((date) => ({
    date,
    status: 'signed' as SignOffStatus,
    signedBy: 'N/A',
    signedAt: 'N/A',
  }));
};

// Active books from bookData
const activeBooks: Book[] = bookData.map((book, index) => ({
  id: String(index + 1),
  name: book.name,
  desk: book.desk,
  primaryTrader: book.primaryTrader,
  secondaryTrader: book.secondaryTrader,
  deskHead: book.deskHead,
  productController: book.productController,
  isRetired: retiredBookNames.includes(book.name),
  signOffs: generateRandomSignOffs(),
  comments: generateSampleComments(String(index + 1), book.name, book.primaryTrader, book.deskHead),
}));

// Retired books from retiredBooksData (no trader assignments)
const retiredBooks: Book[] = retiredBooksData.map((book, index) => ({
  id: `retired-${index + 1}`,
  name: book.name,
  desk: book.desk,
  primaryTrader: 'N/A',
  secondaryTrader: 'N/A',
  deskHead: 'N/A',
  productController: 'N/A',
  isRetired: true,
  signOffs: generateRetiredSignOffs(),
  comments: [],
}));

export const mockBooks: Book[] = [...activeBooks, ...retiredBooks];

// Extract unique product controllers from book data
const productControllers = [...new Set(bookData.map(b => b.productController))];
const traders = [...new Set([...bookData.map(b => b.primaryTrader), ...bookData.map(b => b.secondaryTrader)])];
const deskHeads = [...new Set(bookData.map(b => b.deskHead))];

export const mockUsers: User[] = [
  ...productControllers.map((name, i) => ({
    id: `pc-${i + 1}`,
    name,
    email: `${name.toLowerCase().replace(/\s+/g, '.')}@sefe.eu`,
    role: 'product_controller' as const,
  })),
  ...traders.slice(0, 10).map((name, i) => ({
    id: `tr-${i + 1}`,
    name,
    email: `${name.toLowerCase().replace(/\s+/g, '.')}@sefe.eu`,
    role: 'trader' as const,
  })),
  ...deskHeads.slice(0, 5).map((name, i) => ({
    id: `dh-${i + 1}`,
    name,
    email: `${name.toLowerCase().replace(/\s+/g, '.')}@sefe.eu`,
    role: 'desk_head' as const,
  })),
];

export const currentUser: User = mockUsers[0]; // First Product Controller

// Include all desks from both active and retired books
const allDesks = [...new Set([...bookData.map(b => b.desk), ...retiredBooksData.map(b => b.desk)])];
export const desks = allDesks.sort();
